### ISSUE TITLE
[Feature Request] implement git tag

### ISSUE THREAD

**Issue by digital-mystik** [rusty-snake/firecfg.py#5]
For packaging purposes, namely for a PKGBUILD (for use in Arch + its derivatives), could you please add a git tag so the package version would reflect the git release?

Thanks

-------

Additionally, not sure if you are familiar with PKGBUILDs, but here is my go at it (please let me know if I am missing anything as in having to use install commands before I publish to the AUR)
```
pkgname=python-firecfg-git
pkgver=0.0.4
pkgrel=1
pkgdesc="An improved firecfg written in python"
arch=('any')
url="https://github.com/rusty-snake/firecfg.py"
license=("GPL3")
depends=('python' 'firejail')
makedepends=('python-setuptools' 'git')
optdepends=('apparmor')
source=("${pkgname}::git+https://github.com/rusty-snake/firecfg.py.git#branch=master")

b2sums=('SKIP')

pkgver() {
    cd "${pkgname}"
    git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
    cd "$srcdir/$pkgname"
    python setup.py build
}

package() {
    cd "$srcdir/$pkgname"
    python setup.py install --root="$pkgdir" --optimize=1 --skip-build
}
```

**Comment by rusty-snake** [comment]
> For packaging purposes, namely for a PKGBUILD (for use in Arch + its derivatives), could you please add a git tag so the package version would reflect the git release?

Yes, I'll start tagging.

> Additionally, not sure if you are familiar with PKGBUILDs, but here is my go at it

Not really familiar. However @glitsj16 has also something done.

> please let me know if I am missing anything as in having to use install commands before I publish to the AUR

Not sure about the packaging guidelines but did you considered `firecfg.py setup` in a post-transaction-scriptlet (IDK how pacman calls them).

> optdepends=('apparmor')

firecfg.py itself has no AA support.

**Comment by ghost** [comment]
@rusty-snake Thanks for the ping. It would be great if this gets into the AUR or community somehow.

@digital-mystik See https://github.com/rusty-snake/firecfg.py/issues/3 for issues I stumbled on when attempting a PKGBUILD myself. I've not gotten around to finishing it, but you can find what I have [here](https://gist.github.com/glitsj16/f52b314ee59f2da28310dbfcce4e762e). Feel free to take whatever you think is useful, it doesn't differ all that much from yours on first glance.

**Comment by rusty-snake** [comment]
v0.0.5 tag is out: https://github.com/rusty-snake/firecfg.py/tree/v0.0.5

v0.0.6 will likely happen when I finish https://github.com/rusty-snake/firecfg.py/tree/maybe-firejail-wrapper.
